# Project Information
site_name: Hyperledger Blockchain Performance Reports
site_description: Reporting site for Hyperledger blockchain performance measured using Hyperledger Caliper
site_url: https://pages.github.ibm.com/BlockchainAB/BlockchainPlatformGuide

# Repository Information
repo_name: 'Caliper Benchmarks'
repo_url: 'https://github.com/hyperledger/caliper-benchmarks'

# Navigation/Pages
nav:
    - Overview: index.md
    - Composer:
      - Overview: content/technologies/composer/composer.md
    - Fabric:
      - Overview: content/technologies/fabric/fabric.md
      - v1.4.x:
        - v1.4.0:
          - API:
            - NodeJS: content/common/inprogress.md
            - Java: content/common/inprogress.md
          - Scenario:
            - NodeJS: content/common/inprogress.md
            - Java: content/common/inprogress.md
          - Sample:
            - NodeJS: content/common/inprogress.md
            - Java: content/common/inprogress.md
    - Iroha:
      - Overview: content/technologies/iroha/iroha.md
    - Community:
      - RocketChat: content/community/chat.md
      - Contribute: content/community/contribute.md
    - License : content/license.md


# Configuration
theme:
  name: material
  language: 'en'
  # palette:
  #   primary: green
  #   accent: blue
  # logo:
  #   icon: link
  # feature:
  #   tabs: true

# Social Links
extra:
  social:
    - type: github
      link: https://github.com/hyperledger/caliper-benchmarks